AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  devops-test

  Sample SAM Template for devops-test
  
Parameters:
  EnvStage:
    Type: String
    Default: "DEV"
  VpcSecurityGroup:
    Type: String
    Default: "sg-00000000000000000"
  VpcSubnet1:
    Type: String
    Default: "subnet-00000000000000000"
  VpcSubnet2:
    Type: String
    Default: "subnet-00000000000000000"
  VpcSubnet3:
    Type: String
    Default: "subnet-00000000000000000"
  EnvRdsMysqlSecret:
    Type: String
    Default: "devops/test"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  ApiAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !Ref VpcSecurityGroup
        SubnetIds:
          - !Ref VpcSubnet1
          - !Ref VpcSubnet2
      Environment:
        Variables:
          STAGE: !Ref EnvStage
          RDS_MYSQL_SECRET: !Ref EnvRdsMysqlSecret
      Events:
        ApiApp:
          Type: Api
          Properties:
            Path: /api
            Method: get
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./coding/api-app
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ApiAppApi:
    Description: "API Gateway endpoint URL for Prod stage for Api App function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/"
  ApiAppFunction:
    Description: "Api App Lambda Function ARN"
    Value: !GetAtt ApiAppFunction.Arn
  ApiAppFunctionIamRole:
    Description: "Implicit IAM Role created for Api App function"
    Value: !GetAtt ApiAppFunctionRole.Arn
